---
title: "testing-distributions"
author: "Milla Juntunen"
date: '2022-06-29'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library("readxl")
library("dplyr")

parse_file.function <- function(file_location, sheet_name) {
  
  # Reading the file and deleting empty rows
  df <- na.omit(read_excel(file_location, sheet_name))
  print(df)
  
  # Making empty list
  list_data <- list()
  
  # Counting rows
  rows = nrow(df) 
  row <- 1
  
  # Reading the excel row by row
  for (row in 1:rows){
    
    # Reading data from a row
    row_data <- df[row,]
    
    #Parsing:
    
    # Defining the edge between nodes in flowchart and/or excel
    from <- as.character(select(row_data, from))
    to <- as.character(select(row_data, to))
    edge_name <- paste(from, to, sep = " - ")
    
    # Limits for the times between events
    lower <- as.numeric(select(row_data, start))
    upper <- as.numeric(select(row_data, end))

    # Listing parsed information
    list_data[row] <- list(c(from, to, edge_name, lower, upper))
  }
  return(list_data)
}
```


```{r}
check_vehicle.function <- function(vehicle, list_data, from){
  # I don't know whether to use case or if clauses. This looks soooo messy.

  if(grepl(vehicle, "Ambulance leaving", fixed = TRUE)){
    to <- "Ambulance leaving"
    } else if (grepl(vehicle, "Ambulance + doctor leaving", fixed = TRUE)){
    to <- "Ambluance + doctor leaving"
    } else if (grepl(vehicle, "Helicopter leaving", fixed = TRUE)){
    to <- "Helicopter leaving"
    } else if (grepl(vehicle, "Fire truck leaving", fixed = TRUE)){
    to <- "Fire truck leaving + doctor leaving"
    }
    ret <- c(from, to)
    return(ret)
  }
  
  
  
  
  #for (i in 1:length(data)){
    
    #row <- data[i]
    
    #data_from <- as.character(lapply(row,'[[',1))
    #data_to <- as.character(lapply(row,'[[',2))
    
    #comparing data_to and vehicle if it is a match
    #comp <- grepl(vehicle, data_to)
    
    #cat(data_from, " is current data_from")
    #cat(data_to, " is current data_to")
    #cat(comp, "is value in comp")
   
    # Must check that the correct vehicle is in the "to"
    #if(data_from == from && comp){
      #to <- data_to
      #print("Jippii")
      #}
    
  
  #}
  #ret <- c(from, to)
  #return("Jippii")
#}
```

```{r}
time_calculator.function <- function(from_to, total_time_count, infusion_time_count, data, stop_sign, infusion_starts){
  
  # Calculating the time between events.
  # First getting the lower and upper limits for the time distribution from the data
  from <- from_to[1]
  to <- from_to[2]
  
  i <- 1
  j <- 1
  
  for (i in 1:length(data)){
  
  # Checking if it is time to stop and exit the loop
  if(from == stop_sign) {break}
  
  # Getting the "from" and "to" from the data list
  row <- data[i]
  data_from <- as.character(lapply(row,'[[',1))
  data_to <- as.character(lapply(row,'[[',2))

  #Comparing the datas. If those match, then getting the distribution limits. 
  if(data_from == from && data_to == to) { 
    lower <- as.numeric(lapply(row,'[[',4))
    upper <- as.numeric(lapply(row,'[[',5))
    
    # Updating the total_time_count
    random_time <- runif(1, lower, upper)
    total_time_count <- total_time_count + random_time
    
    #If infusion has started, updating also infusion_time_count
    if(infusion_starts == TRUE) {
      infusion_time_count <- infusion_time_count + random_time
      }
    # Some printing to see if this works at all
    cat("\n")
    cat(as.character(lapply(row,'[[',3)),"\n")
    cat(lower, " is the lower limit for the time distribution\n")
    cat(upper, " is the upper limit for the time distribution\n")
    cat(random_time, " was the randomized time between limits\n")
    cat(total_time_count, " is the time that has now passed\n")
    cat(infusion_time_count, " is the time that has passed since the infusion started\n\n")

    # Getting the next node, this is not the best way to do it
    # "to" is the next "from"
    # Must find the other "to", done below
    from <- to
    cat(from, "\n")
    for (j in 1:length(data)){
      row <- data[j]
      data_from <- as.character(lapply(row,'[[',1))
      if(data_from == from){
        to <- as.character(lapply(row,'[[',2))
      }
    }
  }
  }
  
  cat(data_from, "is the data_from at the end\n")
  cat(data_to, "is the data_to at the end\n")
  cat(from, "is the from at the end\n")
  cat(to, "is the to at the end\n")
  
  ret <- c(from, to, total_time_count, infusion_time_count)
}
```

```{r}
### MAIN FILE STARTS HERE

infusion_starts <- FALSE
# Vectors of which vehicles go to the scene and which are used to transport the patient to the hospital
vehicles_to <- c("Ambulance", "Ambulance + doctor", "Helicopter", "Fire truck")
vehicles_from <- c("Ambulance", "Ambulance + doctor", "Helicopter")

file_location <- "C:\\Projektit\\whole_blood_research\\excel\\EmergencyProcess_EdgeTimes.xlsx"
sheet_name_a <- "test_times_a"
sheet_name_b <- "test_times_b"


# Reading the file, listing information from the sheets
list_data_a <- parse_file.function(file_location, sheet_name_a)
list_data_b <- parse_file.function(file_location, sheet_name_b)

#cat("Printing listed data from chart A (infusion starts on the scene)\n\n")
#print(list_data_a)

#cat("Printing listed data from chart B (infusion starts during transport)\n\n")
#print(list_data_b)

# Drawing the vehicle to go to the scene
vehicle <- vehicles_to[sample(1:length(vehicles_to), 1)]
cat(vehicle, " is the vehicle to rush to the scene!\n")
# Getting the first "time-between-events" edge from the function, also checking if the vehicle is okay
from <- "Risk analysis"
from_to <- check_vehicle.function(vehicle, list_data_a, from)
print(from_to)


# Starting the time-calculator, counting until "Meeting the patient":
# Assuming that the process go by chart A until deciding when to start transfusion
# Counting times until "Meeting the patient"
total_time_count <- 0
infusion_time_count <- 0
stop_sign <- "Meeting the patient"
current_stage <- time_calculator.function(from_to, total_time_count,infusion_time_count, list_data_a, stop_sign, infusion_starts)

# Drawing whether the infusion starts on the scene or during transportation
# if infusion starts on the scene (after meeting the patient), should follow chart b
# Assuming still the chart A to see if this works at all
starting <- c("On the scene", "During transportation")
infusion_startpoint <- starting[sample(1:length(starting),1)]
#print(infusion_start_point)

# Counting again until "Packing" (vehicle must be drawn again after that)
cat("\nBack in business!\n")
stop_sign <- "Packing"
infusion_starts <- TRUE

from <- as.character(current_stage[1])
to <- as.character(current_stage[2])
from_to <- c(from, to)

current_stage <- time_calculator.function(from_to, as.numeric(current_stage[3]), as.numeric(current_stage[4]), list_data_a, stop_sign, infusion_starts)

# Time to draw a (new) vehicle
# Remember to use vehicles_from!

vehicle <- vehicles_from[sample(1:length(vehicles_from), 1)]
cat(vehicle, " is the vehicle to rush to the hospital!\n")

# Getting the first "time-between-events" edge from the function, also checking if the vehicle is okay
from_to <- check_vehicle.function(vehicle, list_data_a, current_stage[1])











```

