---
title: "testing-ggplot"
author: "Milla Juntunen"
date: '2022-06-27'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
source("parsing_edgetimes_excel_version2.R")
library("readxl")
library("ggplot2")
library("dplyr")
library("npreg")

# Reading the data from excel

df <- read_excel("C:\\Projektit\\whole_blood_research\\excel\\Emergencyprocess_PHBT_splines.xlsx", sheet = "yritys")


# Filtering rows (only some of them are useful at a time)


PRBCS_and_plasma_data <- filter(df, products == "plasma and/or RBCs" )


print(df)

print(PRBCS_data)
print(PRBCS_and_plasma_data)
```

```{r}
# Filtering rows (only some of them are useful at a time)
PRBCS_data <- filter(df, products == "O-negative PRBCs" )
print(PRBCS_data)

# Drawing points from the PRCB data
ggplot(PRBCS_data, aes(x = time, y = mortality) ) +
    geom_point() +
    geom_line() +
    geom_smooth(aes(color="No special method or formula"), se = FALSE,  linetype = 1) +
    geom_smooth(method="lm", aes(color="Linear Model"), formula= (y ~ x), se = FALSE, linetype = 2) +
    geom_smooth(method="lm", aes(color="2. deg polynome"), formula= (y ~ poly(x,2)), se = FALSE, linetype = 3) +
    geom_smooth(method = "lm", aes(color="Log model"), formula = y~log(x), se = FALSE, linetype = 3) +
    guides(color = guide_legend("Model Type"))

# According to the pictures made from code above, it seems that the log model has the best match to data points (not a good model but using it anyway)

# Plotting data from the excel
ggplot(data = PRBCS_data, aes(x = time, y = mortality)) + 
  geom_point() +
  geom_smooth(method = "lm", aes(color="Log model"), formula = y~log(x), se = FALSE, linetype = 1)+
  guides(color = guide_legend("Model Type"))

# Making simulated data
simulated_times <- make_timepoints.function(20)
my_model <- lm(mortality~log(time), data = PRBCS_data)
variable_time <- data.frame(time=simulated_times)
predicted_y <- predict(object = my_model, newdata = variable_time)

# Making combined dataframe from original and simulated data
original.data <- data.frame(time = PRBCS_data$time, mortality = PRBCS_data$mortality)
simulation.data <- data.frame(time = simulated_times, mortality = predicted_y)
all.data <- rbind(original.data, simulation.data)

# Plotting the combined data and the simulated and original points
ggplot(all.data, aes(x = time, y = mortality))+
  geom_smooth(method = "lm", aes(color="Log model"), formula = y~log(x), se = FALSE, linetype = 1)+
  geom_point(data = original.data) +
  geom_point(data = simulation.data, color = "blue")+
  guides(color = guide_legend("Model Type"))

```


```{r}
# Same for PRBCS_and_plasma_data:
PRBCS_and_plasma_data <- filter(df, products == "plasma and/or RBCs" )
print(PRBCS_and_plasma_data)

# Fitting different curves (lol this is sooo wroong)
ggplot(PRBCS_and_plasma_data, aes(x = time, y = mortality) ) +
    geom_point() +
    geom_line() +
    geom_smooth(aes(color="No special method or formula"), se = FALSE,  linetype = 1) +
    geom_smooth(method="lm", aes(color="Linear Model"), formula= (y ~ x), se = FALSE, linetype = 2) +
    geom_smooth(method="lm", aes(color="2. deg polynome"), formula= (y ~ poly(x,2)), se = FALSE, linetype = 3) +
    geom_smooth(method = "lm", aes(color="Log model"), formula = y~log(x), se = FALSE, linetype = 3) +
    guides(color = guide_legend("Model Type"))

# Making simulated data (using same simulated time points as earlier)
my_model <- lm(mortality~log(time), data = PRBCS_and_plasma_data)
variable_time <- data.frame(time=simulated_times)
predicted_y <- predict(object = my_model, newdata = variable_time)

# Making combined data frame from original and simulated data
original.data <- data.frame(time = PRBCS_and_plasma_data$time, mortality = PRBCS_and_plasma_data$mortality)
simulation.data <- data.frame(time = simulated_times, mortality = predicted_y)
all.data <- rbind(original.data, simulation.data)

# Plotting the combined data and the simulated and original points
ggplot(all.data, aes(x = time, y = mortality))+
  geom_smooth(method = "lm", aes(color="Log model"), formula = y~log(x), se = FALSE, linetype = 1)+
  geom_point(data = original.data) +
  geom_point(data = simulation.data, color = "blue")+
  guides(color = guide_legend("Model Type"))



```
```{r}
# Same for whole blood:
WB_data <- filter(df, products == "LTOWB" )
print(WB_data)

# Fitting different curves (lol this is sooo wroong)
ggplot(WB_data, aes(x = time, y = mortality) ) +
    geom_point() +
    geom_line() +
    geom_smooth(aes(color="No special method or formula"), se = FALSE,  linetype = 1) +
    geom_smooth(method="lm", aes(color="Linear Model"), formula= (y ~ x), se = FALSE, linetype = 2) +
    geom_smooth(method="lm", aes(color="2. deg polynome"), formula= (y ~ poly(x,2)), se = FALSE, linetype = 3) +
    geom_smooth(method = "lm", aes(color="Log model"), formula = y~log(x), se = FALSE, linetype = 3) +
    guides(color = guide_legend("Model Type"))

# Making simulated data (using same simulated time points as earlier)
my_model <- lm(mortality~log(time), data = WB_data)
variable_time <- data.frame(time=simulated_times)
predicted_y <- predict(object = my_model, newdata = variable_time)

# Making combined data frame from original and simulated data
original.data <- data.frame(time = WB_data$time, mortality = WB_data$mortality)
simulation.data <- data.frame(time = simulated_times, mortality = predicted_y)
all.data <- rbind(original.data, simulation.data)

# Plotting the combined data and the simulated and original points
ggplot(all.data, aes(x = time, y = mortality))+
  geom_smooth(method = "lm", aes(color="Log model"), formula = y~log(x), se = FALSE, linetype = 1)+
  geom_point(data = original.data) +
  geom_point(data = simulation.data, color = "blue")+
  guides(color = guide_legend("Model Type"))
```
Well I guess that there cannot be negative mortality, so this model is pretty bad. 
```{r}


linear.model <-lm(mortality ~ time, WB_data)
log.model <-lm(log(mortality) ~ time, WB_data)
log.model.WB <- data.frame(x = WB_data$time,
                           y = exp(fitted(log.model)))

ggplot(WB_data, aes(x = time, y = mortality) ) +
    geom_point() +
    geom_smooth(aes(color="Method or formula not specified"), se=FALSE, linetype = 1) +
    geom_smooth(method="lm", aes(color="Linear Model"), formula= (y ~ x), se=FALSE, linetype = 2) +
    geom_smooth(method="lm", aes(color="2. degree polynome"), formula= (y ~ poly(x,2)), se=FALSE, linetype = 3) +
    geom_smooth(method="loess", aes(color="Exp Model"), formula= (y ~ exp(x)), se=FALSE, linetype = 5) +
    geom_line(data = log.model.WB, aes(x, y, color = "Log Model"), size = 1, linetype = 6) + 
    guides(color = guide_legend("Model Type"))

```

